"""Guards on the database schema itself.

Two real defects motivated these tests. Model modules that were not imported
where metadata is registered went missing in different ways: absent from
``alembic/env.py`` they read as deleted tables, so an autogenerated revision
would have emitted ``drop_table`` for live data; absent from
``db_maintenance`` they were never created at all, and a fresh install came up
without the salary tables.
"""

import importlib
import pkgutil

import app.models
from app.database import Base
from app.models import entities  # noqa: F401 - populate metadata for these tests
from app.models import intelligence  # noqa: F401
from app.models import salary  # noqa: F401


def _model_modules() -> set[str]:
    return {
        module.name
        for module in pkgutil.iter_modules(app.models.__path__)
        if module.name != "mixins"
    }


def test_db_maintenance_registers_every_model_before_create_all():
    """Importing app.db_maintenance must register every model module's tables.

    Run in a subprocess because this is about import order: inside the test
    session other modules have already populated the shared metadata, which
    would hide exactly the defect being guarded against.
    """
    import json
    import subprocess
    import sys
    from pathlib import Path

    root = Path(__file__).resolve().parents[1]
    probe = (
        "import importlib, json, pkgutil;"
        "import app.db_maintenance;"  # the production entry point, imported alone
        "from app.database import Base;"
        "import app.models;"
        "before=set(Base.metadata.tables);"
        "[importlib.import_module('app.models.'+m.name)"
        " for m in pkgutil.iter_modules(app.models.__path__)];"
        "print(json.dumps(sorted(set(Base.metadata.tables)-before)))"
    )
    result = subprocess.run(
        [sys.executable, "-c", probe],
        cwd=root,
        capture_output=True,
        text=True,
        env={"PATH": "/usr/bin:/bin", "DATABASE_URL": "sqlite:///:memory:"},
    )
    assert result.returncode == 0, result.stderr
    missed = json.loads(result.stdout.strip().splitlines()[-1])

    assert missed == [], (
        "app/db_maintenance.py does not import every model module, so "
        f"create_all skips these tables on a fresh install: {missed}"
    )


def test_alembic_env_and_db_maintenance_agree_on_model_modules():
    """Both schema entry points must import the same set of model modules."""
    from pathlib import Path

    root = Path(__file__).resolve().parents[1]
    env_source = (root / "alembic" / "env.py").read_text(encoding="utf-8")
    maintenance_source = (root / "app" / "db_maintenance.py").read_text(
        encoding="utf-8"
    )

    for name in _model_modules():
        assert name in env_source, f"alembic/env.py does not import models.{name}"
        assert name in maintenance_source, (
            f"app/db_maintenance.py does not import models.{name}"
        )


def test_core_financial_tables_exist_in_metadata():
    """The tables payroll depends on, named explicitly so a rename is caught."""
    for table in (
        "couriers",
        "bonus_plans",
        "payroll_periods",
        "payroll_snapshots",
        "payroll_adjustments",
        "courier_debts",
        "operational_financial_snapshots",
        "salary_structures",
        "salary_components",
        "rider_salary_assignments",
    ):
        assert table in Base.metadata.tables, f"{table} is missing from the schema"
